


create table tokens (
  id BIGINT NOT NULL PRIMARY KEY,
  uuid VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  creationTime TIMESTAMP NOT NULL,
  expirationTime TIMESTAMP NOT NULL,
  isSignUp BOOLEAN NOT NULL
);

create table users (
  id BIGINT NOT NULL PRIMARY KEY,
  userId VARCHAR(255),
  email VARCHAR(255),
  avatarUrl VARCHAR(255),
  name VARCHAR(255),
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

create table user_profiles (
  id BIGINT NOT NULL PRIMARY KEY,
  userId BIGINT NOT NULL REFERENCES users(id),
  providerUserId VARCHAR(255) NOT NULL,
  providerId VARCHAR(255) NOT NULL,
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  fullName VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  avatarUrl VARCHAR(255),
  authMethod VARCHAR(255) NOT NULL,
  token VARCHAR(255),
  secret VARCHAR(255),
  accessToken VARCHAR(255),
  tokenType VARCHAR(255),
  expiresIn INTEGER,
  refreshToken VARCHAR(255),
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

create table follows (
  id BIGINT NOT NULL PRIMARY KEY,
  fromUserId BIGINT NOT NULL REFERENCES users(id),
  toUserId BIGINT NOT NULL REFERENCES users(id),
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE dreams (
  id BIGINT NOT NULL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  authorId BIGINT NOT NULL REFERENCES users(id),
  viewCount INT DEFAULT 0,
  acessRight ENUM('me', 'friends', 'public', 'custom') NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


create table comments (
  id BIGINT NOT NULL PRIMARY KEY,
  text TEXT NOT NULL,
  authorId BIGINT NOT NULL REFERENCES  users(id),
  dreamId BIGINT NOT NULL REFERENCES dreams(id),
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


create table dream_goods (
  id BIGINT NOT NULL PRIMARY KEY,
  dreamId BIGINT NOT NULL REFERENCES dreams(id),
  userId BIGINT NOT NULL REFERENCES users(id),

  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
/*

create table spam (
  id BIGINT NOT NULL PRIMARY KEY,

  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
 */
